# Site settings
title: ShoRAH 2
email: shorah@bsse.ethz.ch
url: https://cbg-ethz.github.io/shorah
description: "ShoRAH : Short Reads Assembly into Haplotypes."
keywords: "bioinformatics, genetic diversity"
skills: "Short Reads Assembly into Haplotypes"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A6A6 #80B3FF
  #primary-rgb: "24,288,156" #"128,179,255"
  #secondary: 2c3e50 #FD6E8A
  secondary: 3D1308 #A2122F
  secondary-dark: 011627 #A2122F

# Footer settings
footer:
  copyright: abc
  location: Developed at
  social: Code
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/cbg-ethz/shorah

# Postal address (add as many lines as necessary)
address:
  - line: ETH Zurich
  - line: Switzerland

# Credits content
credits: 'A list of contributors is found on GitHub'

# Build settings
markdown: kramdown
permalink: pretty
